---
title: "linear_models"
author: "Misbath Daouda"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

Data cleaning
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

First linear model 
```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)
#Bronx is reference category because when nothing is specified, takes alphabetical order 

summary(fit)
coef(fit)
#Not necessarily recommended

fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)
```

Take a look at factors 
```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro), #puts boro in order of the most frequent 
    room_type = fct_infreq(room_type))
```

Refitting the last model 
```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)

fit %>%
  broom::tidy()

#reference category is now Manhattan (the most frequent)
```

Diagnostics 
```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x=boro, y=resid)) + 
  geom_violin() + 
  ylim(-500, 500)

modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x=stars, y=resid)) + 
  geom_point() + 
  ylim(-500, 500)

modelr::add_predictions(nyc_airbnb, fit)
#predictions = fitted values 

```

Interactions
```{r}
nyc_airbnb %>% 
  lm(price ~ stars * boro + room_type * boro, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

```{r}
nyc_airbnb %>% 
  filter(boro == "Brooklyn") %>% 
  lm(price ~ stars + room_type, data = .) %>%
  broom::tidy()
```

Could repeat this for each boro, but easier to map instead. 

```{r}
nyc_airbnb %>% 
  nest(data = -boro) %>% 
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         results = map(models, broom::tidy)) %>% 
  select(boro, results) %>% 
  unnest(results)
```

```{r}
manhattan_airbnb =
  nyc_airbnb %>% 
  filter(boro == "Manhattan")

manhattan_nest_lm_res =
  manhattan_airbnb %>% 
  nest(data = -neighborhood) %>% 
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest(models)

manhattan_nest_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

